### PR TITLE
added pagination to the calls

### PR DESCRIPTION
**Pull request by robevansuk**
Added pagination to the calls that made sense. tidied up the project dependencies (might have done that last time). provided better documentation about whats offered from this client library. more tests (warning: a lot of untested methods as well - these are provided as a convenience but require integration with the coinbase api really since they rely on coinbase account details). Another version bump. Added payments/transfers/withdrawal api calls. Changed name of everything to GDAX rather than coinbase since there is already a coinbase api which makes it confusing otherwise. Report calls implemented.

Outstanding - comprehensive tests for all the new endpoints. Will get these added in time but need the sandbox exchange to come back online!

### CODE REVIEW

**Comment by irufus** [comment]
Sorry for the wait

**Comment by robevansuk** [comment]
No worries - I got the websocket feed working by the way. I then went down
the route of trying to build a functioning GUI for the orderbook as I've
noticed in the past that the GDAX website went down but the API was still
up and running. This meant when the price dropped (after the SEC didn't
approve the bitcoin ETF), there were a ton of buy orders which could have
gotten in a lot lower - if only they'd had access. So I thought a
downloadable, usable GUI front end might be a good work around for this.
I've not spent any time on it for the past few weeks as I went on holiday
and haven't managed to start back up again yet - a lot going on. Anyway I
wondered how good you were with orderbook stuff? Seems like you may have a
background in it? Is it something you could be interested in working on?
Regards,
Rob

**Comment by irufus** [comment]
Oh yeah I have a lot going as well (starting a new job soon)

When I originally started this project my intent was building a platform that would add more features than what Coinbase Exchange (GDAX) offered like automatic trading, signal trading and peer trading.  So building separate features like a usable GUI for the order book would be beneficial.

Right now the current order book on GDAX is very chaotic and could probably use something that is more user friendly and useful. (Not a fan of top-down order books)  I see a lot of features in platforms like ThinkOrSwim (ThinkTDA) that would certainly help with this issue. 

This is something I am interested in working on and will try to take a look at starting next week. (Hopefully earlier)

**Comment by robevansuk** [comment]
Good news all round! Are you going anywhere exciting for your next role?
I'm not familiar with ThinkOrSwim so will have to see if I can find out
more about it.

Here's the link https://github.com/robevansuk/gdax-java/tree/websocketfeed
- you need to supply your own api key/secret/etc. (don't commit them). See
if you can get it running - think the start up command is just:

./gradlew bootRun                     or the equivalent for Windows.

Hopefully start back up on this some day soon.

**Comment by venkateshthallam** [comment]
@robevansuk Quick question about the websocket example. I put the following code in a method which I am calling at the startup.

``	Subscribe message = new Subscribe();
    	message.setType("subscribe");
    	message.setProduct_ids(product_ids);
    	System.out.println("wsfeed is "+wsfeed+" orderBookView is "+orderBookView);
    	if(wsfeed!=null)
    	wsfeed.subscribe(message, orderBookView);

For some reason, the onOpen() method in the websocketfeed.java doesn't initialize userSession and the sendMessage is failing with null pointer. I understand that it happens when there is no event fired as the socket is not opened. But I fail to see the actual reason while socket connection is not working. 

I have put all the necessary parameters in my property file and that doesn't seem to be the issue. Appreciate any direction on how to resolve this or any actual working example. I am using this in a Spring boot project by the way.

**Comment by robevansuk** [comment]
product_ids should be a comma separated list of IDs you want to receive messages for. I'm looking to rewrite this bit anyway as its not working the way it should

**Comment by robevansuk** [comment]
Follow this bit of code which already works.
```private void subscribeAndQueueMsgs(OrderBookView thisOrderBook) {
        log.info("*** Subscribing ***");
        websocketFeed.subscribe(new Subscribe(productIds), thisOrderBook);
    }```

**Pull request merged**
